export const menuName = [
    "Produce",
    "Bakery",
    "Diary & Eggs",
    "Frozen",
    "Meat & Seafood",
    "Canned foods & Soups",
    "Prepared foods",
    "Produce",
    "Bakery",
    "Diary & Eggs",
    "Frozen",
    "Meat & Seafood",
    "Canned foods & Soups",
    "Prepared foods",
    "Produce",
    "Bakery",
    "Diary & Eggs",
    "Frozen",
    "Meat & Seafood",
    "Canned foods & Soups",
    "Prepared foods",
  ];